### ISSUE TITLE
[Suggestion] Expanded Storage Support

### ISSUE THREAD

**Issue by Pop000100** [TimVincii/Terrastorage#1]
### Description

Quick stack doesn't work with [expanded storage](https://modrinth.com/mod/expanded-storage) I tried 14.1.5

**Comment by TimVincii** [comment]
Hi! I'll take a look at what I can do and update you soon.

**Comment by TimVincii** [comment]
Hi again! just rolled out an update that enhances general compatibility with other mods, it also fixes some of the issues with Expanded Storage, but not all of them.

Quick Stack To Nearby Storages now works with the storages added by Expandeded Storage, but it doesn't work perfectly:
By default, when using the Quick Stack to Nearby Storages feature, the entire inventory of a double chest is considered, even if only one half is in the player’s line of sight. However, for double chests whose block entities do not extend LidOpenable, the feature only recognizes the individual inventory of the visible chest block entity. This results in items only being stacked into the visible half of the double chest, instead of the entire inventory

This issue affects all the chests in Expanded Storage, since they were all made from scratch and don't extend LidOpenable, but instead have their own ChestLidController.

I’m committed to fixing this issue in the next version, but in the meantime, you can mitigate it by disabling the line-of-sight check with the command: `/terrastorage line-of-sight-check false`.

For now, I’ll keep this issue open since Expanded Storage isn't fully compatible yet, but you’re welcome to close it if you prefer. Thank you for the suggestion, and I wish you a great day!
