### ISSUE TITLE
[Suggestion] Support for the Unofficial Fabric ports of Sophisticated Backpacks/Storage

### ISSUE THREAD

**Issue by Spyr6** [TimVincii/Terrastorage#11]
### Description

Wondering if there's a chance compatibility can be added for these mods? Currently, the buttons do nothing, and overlap some UI elements.
https://modrinth.com/mod/sophisticated-backpacks-(unoffical-fabric-port)
https://modrinth.com/mod/sophisticated-storage-(unofficial-fabric-port)

![2024-11-03_09 24 11](https://github.com/user-attachments/assets/f3967429-3c93-44b6-84f5-ef2e99334e71)

![2024-11-03_09 24 24](https://github.com/user-attachments/assets/5091ee21-49f1-438e-b7c0-c24acd114e14)

**Comment by TimVincii** [comment]
Hi, thanks for taking the time to make a suggestion!

I was already aware of the issue with Sophisticated Storage/Backpacks on NeoForge when using Sinytra Connector, so it makes sense that similar issues appear with the Fabric ported versions of these mods.

After looking into it, here’s what I found: when using any Terrastorage storage actions, the storage inventory is accessed through the player’s current screen handler. Even for custom storage screens, the screen handler’s `slots` should reference their parent inventory. However, in Sophisticated Storage/Backpacks, while `slots` are present, they lack these necessary references, blocking access to the inventory and causing compatibility issues.

While it might be technically possible to address this through some complex workarounds, I’d rather focus my time on other improvements for Terrastorage, since this compatibility issue isn’t really due to Terrastorage itself.

Regarding the overlapping UI elements, I’m actually planning to make button positioning fully customizable, so this should be addressed in the near future.

With all that covered, I'll now be closing this issue as completed. Thanks again for your suggestion, and I wish you a great day!
