### ISSUE TITLE
[Suggestion] Setting to allow new stacks to be created when quickstacking

### ISSUE THREAD

**Issue by Spyr6** [TimVincii/Terrastorage#12]
### Description

Quickstacking only works when existing stacks in a container aren't full. this was mentioned on the mod page and seems like an intentional feature. Perhaps a setting in the menu or maybe an entry in the config files could be added to make items quickstack even if existing stacks in the chest are full, as long as there is space? This is a great mod otherwise.

**Comment by TimVincii** [comment]
Hi, thanks for taking the time to make a suggestion!

As you mentioned, Quick Stacking currently only targets non-full stacks of the item being quick stacked, without filling any empty slots. This was intentional to keep it in line with how it works in Terraria.

That said, I can definitely see where you’re coming from, and I really like this suggestion. If I decide to add an option for this, I’d likely make it apply to both regular chest quick stacking and the Quick Stack to Nearby Chests feature. But if you had just one of these functions in mind, please let me know.

Looking forward to hearing back from you, and thanks again for the feedback!

**Comment by Spyr6** [comment]
> Hi, thanks for taking the time to make a suggestion!
> 
> As you mentioned, Quick Stacking currently only targets non-full stacks of the item being quick stacked, without filling any empty slots. This was intentional to keep it in line with how it works in Terraria.
> 
> That said, I can definitely see where you’re coming from, and I really like this suggestion. If I decide to add an option for this, I’d likely make it apply to both regular chest quick stacking and the Quick Stack to Nearby Chests feature. But if you had just one of these functions in mind, please let me know.
> 
> Looking forward to hearing back from you, and thanks again for the feedback!

I didn't realize this was also how it worked in Terraria, it's been a while since I've played. Making this setting apply to both quickstack functions would be awesome! But I guess if you wanna snag some customizability points, a separate setting for both functions would also be sweet, as I imagine some people might prefer one or the other depending on the quickstack function, but that's completely up to you.

**Comment by TimVincii** [comment]
Hey again, thanks for your patience, you got me thinking about this, so I decided to do some deeper testing. I’d like to apologize, as I was wrong.

After testing, I found that in Terraria, Quick Stacking does indeed move items to a receiving chest even if all existing stacks of that item are full, as long as there’s at least one stack of that item in the chest, full or not. I’d overlooked this since Terraria’s high max stack sizes made it less likely to come up, so I hadn’t tested for it as an edge case.

With this in mind, I'll work on adding an option for this behavior. I’ll be closing this issue as of now, and thanks again for the suggestion. Have an awesome day!
