### ISSUE TITLE
[Suggestion] Hotkey Sort Button

### ISSUE THREAD

**Issue by 123789g** [TimVincii/Terrastorage#13]
### Description

This mod does a lot of things by itself that makes it great competition vs other inventory tweak mods, but one thing I think it's lacking is a hokey-able sort button. Yes there's a permanent widget in your inventory and in chests, but I'd like to bind that sort widget to a keybind (like middle mouse) to sort whatever inventory my mouse hovers over.

**Comment by TimVincii** [comment]
Hey! thanks for the suggestion, and sorry for taking so long to respond.

I like the idea, makes sorting inventories smoother and faster, I'll definitely work on adding it, but since I'm quite busy at the moment with previous suggestions, expect this addition to go through in the version after the next.

I'll close this issue as of now, and thanks again for the suggestion. I'll make sure to reply here once the update containing the feature will be out, have a great day!

**Comment by TimVincii** [comment]
Hey again! 

Just finished releasing version 1.2.1 that adds this keybind, you can now hover over a slot and press it to quickly sort the inventory.
I set the default key to **R** as to not conflict with Minecraft's Pick Block key, but you can customize it to your liking in the controls menu.

Once again, thanks for the suggestion, and have an awesome day!

**Comment by 123789g** [comment]
> Hey again!
> 
> Just finished releasing version 1.2.1 that adds this keybind, you can now hover over a slot and press it to quickly sort the inventory. I set the default key to **R** as to not conflict with Minecraft's Pick Block key, but you can customize it to your liking in the controls menu.
> 
> Once again, thanks for the suggestion, and have an awesome day!

Ayeeee! Thank you!
