### ISSUE TITLE
[Suggestion] Moving favorited items with keybinds 

### ISSUE THREAD

**Issue by aktivnogogubam** [TimVincii/Terrastorage#9]
### Description

Firstly I wanna say how much I ADORE this mod and the favoriting feature is something I have been looking for for SOOOO long. There is one issue and it's not being able to move my favorited items using keybinds (1-9). I know some people might prefer it that way so I think an option which allows you to toggle this setting would be very nice. Please consider it :)

**Comment by TimVincii** [comment]
Hi! Thanks for taking the time to make a suggestion, and thank you for the kind words! I'm really glad Terrastorage is proving useful to people.

While you can move favorited items using hotbar keybinds, this won’t work if the keybind you press corresponds to a slot that contains a favorited item. For example, if you press the "3" key while hovering over another slot and your third hotbar slot holds a favorited item, the action won’t be performed.

I played with it a bit, and I can completely see where you're coming from, it can feel a bit unnatural at times.

I’d be happy to add an option as you suggested! However, I’m considering one adjustment: I think it would make sense for the action to still be canceled if the hovered slot is outside the player’s inventory. So, after the changes, if you press the "3" key while hovering over another slot and your third hotbar slot contains a favorited item, the action will only go through if the hovered slot is within the player’s inventory.

What do you think? Does that approach sound good, or would you suggest something different for this case?

**Comment by AleksandarGareski** [comment]
Hi thanks so much for reviewing my idea :)

Your approach sounds amazing actually. I doubt much people use 1-9 keybinds to move items to chests and you would still be able to move your items freely in your inventory so I absolutely love your idea I'd be very happy to see it implemented :)

Please message me here when the update goes through so that I download the latest version. Have a nice day!

**Comment by TimVincii** [comment]
Hey again! I just finished updating Terrastorage, and as of version 1.1.4, the change is live. Now, you can use the hotbar keybinds (1-9) to move items within your inventory, even if they’re favorited, as long as the hovered slot is in the player’s inventory.

I actually ended up not adding an option for this behavior, mainly because I felt this approach should’ve been the default from the start, and I imagine most players would prefer it as well. Plus, it keeps things simpler overall.

I'll be closing this issue now, thanks again for taking the time to suggest this change. If you have any other suggestions, or run into any issues, please don't hesitate to reach out again.

Have a great day!
